--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/BatchFarming
branches:
  - main
projects:
  BatchFarming:
    lint:
      phpstan: false
    libs:
      - src: PresentKim/multilingual-resource-trait/multilingual-resource-trait
        version: ^1.0.0
...
